apiVersion: v1
kind: Service
metadata:
  name: CD-service
spec:
  selector:
    app: CD-mlops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # ✅ Exposes external IP